version: "3.7"

services:

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - "../api:/app"
    ports:
      - 8081:8080

  postgres:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_USER: svoyak
      POSTGRES_PASSWORD: top_secret_goes_here
    volumes:
      - "../db/migrations/:/docker-entrypoint-initdb.d"
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  consul:
    image: consul:latest
    restart: always
    network_mode: host
    ports:
      - 8500:8500
      - 8600:8600

volumes:
  pg_data:
