version: "3.7"

services:
  application:
    restart: always
    build:
      context: ../
      dockerfile: deployments/Dockerfile-application
    volumes:
      - "../../data/uploads:/application/data/uploads"
      - "../../data/logs:/tmp/logs"
      - "../../configs:/application/configs"
    depends_on:
      - postgres
      - session
    ports:
      - 2345:2345 # Remote debug
    networks:
      - app
      - metrics

  session:
    restart: always
    build:
      context: ../
      dockerfile: deployments/Dockerfile-session
    volumes:
      - "../../configs:/application/configs"
    depends_on:
      - postgres
    ports:
      - 2346:2345 # Remote debug
    networks:
      - app
      - metrics

  chat:
    restart: always
    build:
      context: ../
      dockerfile: deployments/Dockerfile-chat
    volumes:
      - "../../configs:/application/configs"
    depends_on:
      - postgres
      - session
    networks:
      - app

  game:
    restart: always
    build:
      context: ../
      dockerfile: deployments/Dockerfile-game
    volumes:
      - "../../configs:/application/configs"
    depends_on:
      - postgres
      - session
    networks:
      - app
      - metrics

  postgres:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_USER: svoyak
      POSTGRES_PASSWORD: top_secret_goes_here
    volumes:
      - "../db/migrations/:/docker-entrypoint-initdb.d"
      - "../../data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      - app

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - "../api:/app"
    networks:
      - app

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - chat
      - session
      - game
      - application
    volumes:
      - "../configs/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../../data/uploads:/data/uploads"
    ports:
      - 3000:3000
    networks:
      - app

networks:
  app:
  metrics:
    external:
      name: metrics
