version: "3.7"

services:
  application:
    restart: always
    build:
      context: ../
      dockerfile: deployments/Dockerfile-application
    volumes:
      - "../data/uploads:/application/data/uploads"
      - "../data/logs:/tmp/logs"
      - "../../configs:/application/configs"
    depends_on:
      - postgres
    ports:
      - 8010:8080
      - 3010:3000

  chat:
    restart: always
    build:
      context: ../
      dockerfile: deployments/Dockerfile-chat
    volumes:
      - "../../configs:/application/configs"
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_USER: svoyak
      POSTGRES_PASSWORD: top_secret_goes_here
    volumes:
      - "../db/migrations/:/docker-entrypoint-initdb.d"
      - "pg_data:/var/lib/postgresql/data"

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - "../api:/app"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - application
      - swagger
    volumes:
      - "../configs/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../data/:/data"
    ports:
      - 3000:3000

volumes:
  pg_data:
