version: "3.7"

services:
  application:
    build:
      context: ../
      dockerfile: deployments/Dockerfile-application
    volumes:
      - "../data/uploads"

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - "../api:/app"

  nginx:
    image: nginx:latest
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../data:/data"
    ports:
      - "3000:3000"