version: "3.7"

services:
  postgres:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_USER: svoyak
      POSTGRES_PASSWORD: top_secret_goes_here
    volumes:
      - "../db/migrations/:/docker-entrypoint-initdb.d"
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - 8080:8080

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - "../api:/app"

#  nginx:
#    image: nginx:latest
#    restart: always
#    depends_on:
#      - swagger
#    volumes:
#      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
#      - "../data:/data"
#    ports:
#      - 3000:3000

volumes:
  pg_data:
